FROM python:3.8-slim-buster
WORKDIR /usr/src/app
COPY . .
RUN pip install -qr requirements.txt
COPY backend  /usr/src/app/

FROM node:10-stretch-slim as nodeimage
WORKDIR /usr/src/app
COPY frontend  /usr/src/app/
RUN npm install
RUN npm run build
FROM nginx
COPY frontend/nginx.conf /etc/nginx/nginx.conf
COPY --from=nodeimage /usr/src/app/build /usr/share/nginx/html
CMD ["python3", "./application.py"]

